import { LeaderboardUser } from '../../core/interfaces/http';

export const MOCK_LEADERBOARD_USERS: LeaderboardUser[] = [
  {
    id: 1,
    name: 'vaugouin',
    avatar: 'https://i.pravatar.cc/150?img=1',
    totalEdits: 530748,
    weeklyEdits: 33666,
    totalPercentage: 17,
    weeklyPercentage: 100,
  },
  {
    id: 2,
    name: 'RuiZafon',
    avatar: 'https://i.pravatar.cc/150?img=6',
    totalEdits: 2581750,
    weeklyEdits: 22643,
    totalPercentage: 52,
    weeklyPercentage: 67,
  },
  {
    id: 3,
    name: 'Shei',
    avatar: 'https://i.pravatar.cc/150?img=2',
    totalEdits: 3088735,
    weeklyEdits: 17508,
    totalPercentage: 63,
    weeklyPercentage: 52,
  },
  {
    id: 4,
    name: 'Samara',
    avatar: 'https://i.pravatar.cc/150?img=7',
    totalEdits: 4927593,
    weeklyEdits: 11650,
    totalPercentage: 100,
    weeklyPercentage: 35,
  },
  {
    id: 5,
    name: 'coltergiest',
    avatar: 'https://i.pravatar.cc/150?img=3',
    totalEdits: 9744,
    weeklyEdits: 9221,
    totalPercentage: 0.2,
    weeklyPercentage: 27,
  },
  {
    id: 6,
    name: 'carlosmenov',
    avatar: 'https://i.pravatar.cc/150?img=8',
    totalEdits: 8647,
    weeklyEdits: 8647,
    totalPercentage: 0.2,
    weeklyPercentage: 26,
  },
  {
    id: 7,
    name: 'Lorilei',
    avatar: 'https://i.pravatar.cc/150?img=4',
    totalEdits: 7916,
    weeklyEdits: 7191,
    totalPercentage: 0.2,
    weeklyPercentage: 21,
  },
  {
    id: 8,
    name: 'moshpotato',
    avatar: 'https://i.pravatar.cc/150?img=9',
    totalEdits: 24032,
    weeklyEdits: 6885,
    totalPercentage: 0.5,
    weeklyPercentage: 20,
  },
  {
    id: 9,
    name: 'strong_style',
    avatar: 'https://i.pravatar.cc/150?img=5',
    totalEdits: 268935,
    weeklyEdits: 6206,
    totalPercentage: 5,
    weeklyPercentage: 18,
  },
  {
    id: 10,
    name: 'talestalker',
    avatar: 'https://i.pravatar.cc/150?img=10',
    totalEdits: 1514988,
    weeklyEdits: 6140,
    totalPercentage: 31,
    weeklyPercentage: 18,
  },
];
